# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/hass_py',
                'doc_host': 'https://ddobrinskiy.github.io',
                'git_url': 'https://github.com/ddobrinskiy/hass_py',
                'lib_path': 'hass_py'},
  'syms': {'hass_py.utils': {'hass_py.utils.foo': ('utils.html#foo', 'hass_py/utils.py')}}}
