# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['find_dir']

# %% ../nbs/00_utils.ipynb 3
from pathlib import Path

# %% ../nbs/00_utils.ipynb 4
def find_dir(dirname: str) -> Path:
    """find dirname in cwd or cwd.parent

    Parameters
    ----------
    dirname : str
        dirname to find

    Returns
    -------
    Path
        path to dirname

    Raises
    ------
    FileNotFoundError
        err if dirname not found

    NotADirectoryError
        err if dirname is not a directory
    """
    cwd = Path.cwd()

    if (cwd / dirname).exists():
        path = cwd / dirname
    elif (cwd.parent / dirname).exists():
        path = cwd.parent / dirname
    else:
        raise FileNotFoundError(f"{dirname} not found in {cwd} or {cwd.parent}")

    if not path.is_dir():
        raise NotADirectoryError(f"{path} is not a directory")

    return path
